Provides support for installing on vanilla kubernetes
hawtio/hawtio-operator pull request #99
Opened 2024-01-12 20:14 UTC by phantomjinx

- Upgrade `client-go`, `k8s.io/api` (0.21.1) and `controller-runtime` (0.9.0) in order to support the current incarnation of Ingress (`networking.k8s.io/v1`);
- Upgrades the deprecated `api/batch/v1beta1` to `api/batch/v1`;
- Formats test results using `gotestfmt`; 
- Provides `capabilities` API for discovering the type of cluster (OpenShift or Kubernetes) based on the existence of installed APIs, also providing the Kubernetes version and/or the OpenShift release version;
- Tidies up function calls by wrapping parameter variables into structs;
- Provides self-signed certificate creation and installation for the `hawtio-online-tls-serving` secret required for k8;
- `cr` and `uninstall` rules for Makefiles;
- Creation of `ingress` for Kubernetes and `route` for OpenShift;

2024-01-15 09:54 UTC, tadayosi requested changes
Can you please split the mere dependency updates from the substantial changes?

1731 files changes make it impossible to review it on GitHub as the browser becomes frozen...

2024-01-15 09:55 UTC, tadayosi commented
You can also format test code separately from the issue.

2024-01-15 13:06 UTC, phantomjinx commented
Checks will fail until https://github.com/hawtio/hawtio-operator/pull/101 has been merged.

2024-01-16 06:39 UTC, tadayosi approved these changes

2024-01-16 10:47 UTC, merged